### ISSUE TITLE
Userscripts end in .user.js not plain .js

### ISSUE THREAD

**Issue by Martii** [Jamie22/FamilySearch-Relationship-Name#1]
If you would like to use the GH to OUJS auto-sync you need to do this with your script. e.g.

Do `$ git mv FamilySearchRelationshipName.js FamilySearchRelationshipName.user.js`; then push it to your repo here on GH; and then reimport it on OUJS to establish the link.

I see that you manually copied/uploaded it over into OUJS but thought you might need a tip with how to do it the correct way.

Thanks for the read.
OUJS Admin

**Comment by Jamie22** [comment]
Got it. Thanks!
